apiVersion: v1
kind: ConfigMap
metadata:
  name: benchmark-sweep-{{ "{{ slice_id }}" }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "benchmark.labels" . | nindent 4 }}
    slice-id: "{{ "{{ slice_id }}" }}"
data:
  sweep.json: |
    {{ "{{ sweep_json }}" }}
