apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vllmService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "benchmark.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.vllmService.port }}
      targetPort: {{ .Values.vllmService.port }}
      protocol: TCP
  selector:
    {{- include "benchmark.selectorLabels" . | nindent 4 }}
